"""add created_at

Revision ID: 3da13e1fd9a2
Revises: 0043ab1b756b
Create Date: 2026-05-26 14:28:49.783036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da13e1fd9a2'
down_revision: Union[str, Sequence[str], None] = '0043ab1b756b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'created_at')
    # ### end Alembic commands ###
