"""create_at updated to UTC with timezone true

Revision ID: b52f0891fca2
Revises: 60a3e2e03ff6
Create Date: 2026-05-26 17:29:34.192497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b52f0891fca2'
down_revision: Union[str, Sequence[str], None] = '60a3e2e03ff6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
